<?php defined('SYSPATH') or die('No direct access allowed.');

/**
 * SMSSync SMS provider
 */
class PingApp_SMS_Provider_Smssync extends Pingapp_SMS_Provider {
	
	/**
	 * @return mixed
	 */
	public function send($to, $message)
	{
		// The SMSSync App on the phone will pick this SMS later for sending
		// For now just send back an autogenerated Tracking ID
		return PingApp_Ping::tracking_id('sms');
	}
}